version: '3'

services:

  frontend:
    build: ./dockerfiles/frontend/
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/:/var/www/html/
    restart: always
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build: ./dockerfiles/backend/
    volumes:
      - ./backend/:/var/www/html/
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    depends_on:
      - database
      - cache

  database:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - database-volume:/var/lib/postgresql/data/

  cache:
    image: redis
    restart: always

volumes:
    database-volume:
