version: '3'

services:

  frontend:
    build:
      context: ./dockerfiles/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "3001:5173"
    volumes:
      - ./frontend/:/var/www/html/
    restart: always
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./dockerfiles/backend/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend/:/var/www/html/
    restart: always
    env_file:
      - .env
    depends_on:
      - database

  # psql -d transcendence -p 5432 --username=sasso -h localhost
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # ONLY IN DEV ENVIRONMENT
    env_file:
      - .env
    volumes:
      - database-volume:/var/lib/postgresql/data/

volumes:
  database-volume:
