version: '3'

services:

  frontend:
    build: ./dockerfiles/frontend/
    ports:
      - "5173:3000"
    volumes:
      - ./frontend/:/var/www/html/
    restart: always
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build: ./dockerfiles/backend/
    ports:
      - "3000:3000" # ONLY IN DEV ENVIRONMENT
    volumes:
      - ./backend/:/var/www/html/
    restart: always
    env_file:
      - .env
    depends_on:
      - database

  # psql -d transcendence -p 5432 --username=sasso -h localhost
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # ONLY IN DEV ENVIRONMENT
    environment:
      POSTGRES_USER: sasso
      POSTGRES_PASSWORD: ossas
      POSTGRES_DB: transcendence


  # redis-cli -h localhost -p 6379
  database-cache:
    image: redis
    ports:
      - "6379:6379" # ONLY IN DEV ENVIRONMENT
    restart: always

