version: '3'

services:

  frontend:
    build: ./dockerfiles/frontend/
    ports:
      - "5173:3000"
    volumes:
      - ./frontend/:/var/www/html/
    restart: always
    env_file:
      - .env

  backend:
    build: ./dockerfiles/backend/
    ports:
      - "3000:3000" # ONLY IN DEV ENVIRONMENT
    volumes:
      - ./backend/:/var/www/html/
    restart: always
    env_file:
      - .env