version: '3'

services:

  frontend:
    build:
      context: ./dockerfiles/frontend/
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/:/var/www/html/
    restart: always
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./dockerfiles/backend/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000" # ONLY IN DEV ENVIRONMENT
    volumes:
      - ./backend/:/var/www/html/
    restart: always
    env_file:
      - .env
    depends_on:
      - database
      - cache

  # psql -d transcendence -p 5432 --username=sasso -h localhost
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # ONLY IN DEV ENVIRONMENT
    env_file:
      - .env
    volumes:
      - database-volume:/var/lib/postgresql/data/

  # redis-cli -h localhost -p 6379
  cache:
    image: redis
    ports:
      - "6379:6379" # ONLY IN DEV ENVIRONMENT
    restart: always

volumes:
  database-volume:
